{% set name = "retina-face" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/retina-face-{{ version }}.tar.gz
  sha256: 7532b136ed01fe9a8cba8dfbc5a046dd6fb1214b1a83e57f3210bd145a91cd73

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5.5
  run:
    - gdown >=3.10.1
    - numpy >=1.14.0
    - opencv >=3.4.4
    - pillow >=5.2.0
    - python >=3.5.5
    - tensorflow >=1.9.0

test:
  imports:
    - retinaface
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/serengil/retinaface
  summary: 'RetinaFace: Deep Face Detection Framework in TensorFlow for Python'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - serengil
    - BastianZim
